services:
  - type: web
    name: dante-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python db_init.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000